# Generated by Django 5.1.6 on 2025-02-22 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='mild_level1', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('unlocked_next', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
