# Generated by Django 5.1.6 on 2025-02-22 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('mild_level1', 'Mild Level 1'), ('mild_level2', 'Mild Level 2'), ('mild_level3', 'Mild Level 3'), ('moderate_level1', 'Moderate Level 1'), ('moderate_level2', 'Moderate Level 2'), ('moderate_level3', 'Moderate Level 3'), ('severe_level1', 'Severe Level 1'), ('severe_level2', 'Severe Level 2'), ('severe_level3', 'Severe Level 3')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('unlocked_next', models.BooleanField(default=False)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gamelevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
